<!-- Main SLIde -->
<div class="grid-container full slide_block">
<div class="grid-x grid-margin-x">
<?php 
echo '<div class="home_carousel cell">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('slide_home')
           ->toHtml();
echo '</div>';

?>
</div>
</div>

<!-- Banner -->
<div class="grid-container full banner_home_prev_wrp">
<div class="grid-x">
<?php 
echo '<div class="sing_banner_home_prev banner_home_prev_1 cell small-12 medium-12 large-6">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('banner_home_prev_01')
           ->toHtml();
echo '</div>';

?>
<?php 
echo '<div class="sing_banner_home_prev banner_home_prev_2 cell small-12 medium-12 large-6">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('banner_home_prev_2')
           ->toHtml();
echo '</div>';

?>
<?php 
echo '<div class="sing_banner_home_prev banner_home_prev_3 cell small-12 medium-12 large-6">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('banner_home_prev_3')
           ->toHtml();
echo '</div>';

?>
<?php 
echo '<div class="sing_banner_home_prev banner_home_prev_4 cell small-12 medium-12 large-6">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('banner_home_prev_4')
           ->toHtml();
echo '</div>';

?>
</div>
</div>

<!-- Last products -->

<div class="grid-container last_prod_home_wrp">
<div class="grid-x">
<?php 
echo '<div class="last_prod_home cell small-12 medium-12 large-12">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('last_arrives_home')
           ->toHtml();
echo '</div>';

?>
</div>
</div>

<!-- First parallax -->

<div class="grid-container full">
<div class="grid-x">
<?php 
echo '<div class="cell small-12">';
echo $block->getLayout()
           ->createBlock('Magento\Cms\Block\Block')
           ->setBlockId('banner_home_01')
           ->toHtml();
echo '</div>';

?>
</div>
</div>


<script>
    require([
        'jquery',
        'slick',
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".home_carousel p").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 1,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    });
</script>
