<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action mailto friend" data-tooltip tabindex="1" title="<?= /* @escapeNotVerified */ __('Email') ?>" data-position="top" data-alignment="center"><span><i class="fas fa-envelope-square"></i></span></a>
<?php endif; ?>
